### ISSUE TITLE
pose_representation wrong initial value

### ISSUE THREAD

**Issue by dimodimi** [duckietown/mooc-exercises#5]
In the first modcon [notebook](https://github.com/duckietown/mooc-exercises/blob/daffy/modcon/solution/01-Representations/pose_representation.ipynb), in the example "moving between frames (from robot frame to map frame)" this initialization: 
`obstacle_angle = 30 # Obstacle angle with respect to Duckiebot (in degrees)` should be 50 degrees.

**Comment by mhered** [comment]
Yes I saw that too
